# fly.toml app configuration file generated for your Django app

app = "royamotorsuk-app"  # Change this to your desired app name
primary_region = "fra"  # Change to your preferred region (fra, iad, sin, etc.)

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/admin/"
  protocol = "http"
  timeout = "2s"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "rmotors_backend.settings"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

[[statics]]
  guest_path = "/app/media"
  url_prefix = "/media/"