from django.core.management.base import BaseCommand
from vehicles.models import Vehicle, VehicleImage

CARS = [
    {
        "make": "Bentley",
        "model": "Continental GT",
        "year": 2023,
        "price": 245000,
        "mileage": 1500,
        "exterior_color": "Onyx Black",
        "interior_color": "Linen",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "6.0L W12",
        "description": """The Bentley Continental GT represents the pinnacle of British luxury grand touring. This exquisite example, finished in Onyx Black with a handcrafted Linen interior, delivers effortless power from its 6.0-liter W12 engine. With just 1,500 miles on the odometer, it presents in pristine condition, indistinguishable from new. The Continental GT combines breathtaking performance with unparalleled comfort, making it the perfect vehicle for both spirited driving and luxurious long-distance journeys.""",
        "features": [
            "Mulliner Driving Specification",
            "Naim for Bentley Premium Audio",
            "Rotating Display",
            "Panoramic Roof",
            "Adaptive Cruise Control",
            "Night Vision",
            "Head-Up Display",
            "Massage Seats",
            "Diamond Knurling Package",
            "City Specification & Touring Specification"
        ],
        "status": "Available"
        },
        {
        "make": "Range Rover",
        "model": "SV Autobiography",
        "year": 2022,
        "price": 195000,
        "mileage": 8500,
        "exterior_color": "Santorini Black",
        "interior_color": "Ebony/Ivory",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "5.0L V8",
        "description": """This Range Rover SV Autobiography represents the ultimate expression of luxury SUV motoring. Finished in striking Santorini Black with a dual-tone Ebony/Ivory interior, this vehicle exudes sophistication. The supercharged 5.0-liter V8 engine provides effortless power, while the long-wheelbase configuration ensures exceptional rear passenger comfort. With just 8,500 miles, this nearly-new example comes with all the refinement, capability, and prestige that defines the Range Rover brand.""",
        "features": [
          "Executive Class Rear Seats",
          "Hot Stone Massage Function",
          "Deployable Tables",
          "Refrigerated Compartment",
          "Meridian Signature Sound System",
          "Pixel-Laser LED Headlights",
          "All-Terrain Progress Control",
          "Digital Rearview Mirror",
          "Soft Door Close",
          "Activity Key"
        ],
        "status": "Available"
      },
      {
        "make": "Rolls-Royce",
        "model": "Ghost",
        "year": 2022,
        "price": 380000,
        "mileage": 3200,
        "exterior_color": "Arctic White",
        "interior_color": "Navy Blue",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "6.75L V12",
        "description": """This Rolls-Royce Ghost embodies effortless luxury with its pristine Arctic White exterior and sumptuous Navy Blue leather interior. Powered by the iconic 6.75-liter V12 twin-turbocharged engine, it delivers a perfect balance of power and refinement. With only 3,200 miles, this nearly-new Ghost features Rolls-Royce\'s groundbreaking Planar Suspension System, providing the famed "magic carpet ride" that isolates passengers from the world outside. This is modern luxury at its finest.""",
        "features": [
          "Starlight Headliner",
          "Bespoke Audio System",
          "Rear Theatre Configuration",
          "Picnic Tables",
          "Illuminated Fascia",
          "Lambswool Floor Mats",
          "Spirit of Ecstasy Illuminated",
          "Rear Massage Seats",
          "Champagne Cooler",
          "Individual Rear Seats"
        ],
        "status": "Available"
      },
      {
        "make": "Aston Martin",
        "model": "DBS Superleggera",
        "year": 2021,
        "price": 275000,
        "mileage": 5800,
        "exterior_color": "Quantum Silver",
        "interior_color": "Obsidian Black",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "5.2L V12",
        "description": """This Aston Martin DBS Superleggera represents the pinnacle of the brand\'s grand touring capabilities. Finished in iconic Quantum Silver with an Obsidian Black interior, this stunning example has covered just 5,800 miles. Powered by a twin-turbocharged 5.2-liter V12 engine producing 715 bhp, the DBS Superleggera combines breathtaking performance with exquisite craftsmanship and British luxury. This particular car features a range of desirable options, making it a collector\'s piece as well as an extraordinary driving machine.""",
        "features": [
          "Carbon Fiber Exterior Package",
          "Bang & Olufsen BeoSound Audio",
          "Ventilated Seats",
          "Carbon Ceramic Brakes",
          "Technology Package",
          "Comfort Package",
          "360-Degree Camera",
          "Triaxial Quilting",
          "Satin Chrome Jewelry Pack",
          "Bespoke Interior Detailing"
        ],
        "status": "Available"
      },
      {
        "make": "Mercedes-Benz",
        "model": "S-Class S680 Maybach",
        "year": 2023,
        "price": 230000,
        "mileage": 2100,
        "exterior_color": "Obsidian Black",
        "interior_color": "Sienna Brown/Black",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "6.0L V12",
        "description": """This Mercedes-Maybach S680 represents the ultimate in luxury sedan transportation. Finished in elegant Obsidian Black with a dual-tone Sienna Brown/Black interior, this vehicle embodies sophistication and presence. Powered by a smooth 6.0-liter V12 engine, it delivers effortless performance with supreme refinement. With just 2,100 miles, this nearly-new example features the very latest technology and comfort features that Mercedes-Benz has to offer, creating a sanctuary of luxury for both driver and passengers.""",
        "features": [
          "Executive Rear Seats with Massage",
          "Burmester High-End 4D Surround Sound",
          "Rear Seat Entertainment",
          "MBUX Interior Assistant",
          "Active Road Noise Compensation",
          "Digital Light with Projection Function",
          "Rear Refrigerator Compartment",
          "Champagne Flute Holder",
          "Night Vision Assist",
          "ENERGIZING Comfort Package"
        ],
        "status": "Available"
      },
      {
        "make": "Ferrari",
        "model": "SF90 Stradale",
        "year": 2022,
        "price": 550000,
        "mileage": 1200,
        "exterior_color": "Rosso Corsa",
        "interior_color": "Nero",
        "fuel_type": "Hybrid",
        "transmission": "Automatic",
        "engine_size": "4.0L V8 Hybrid",
        "description": """This Ferrari SF90 Stradale represents the pinnacle of Ferrari\'s engineering excellence. Finished in the iconic Rosso Corsa with a Nero interior, this hybrid hypercar combines a twin-turbocharged V8 engine with three electric motors to produce a staggering 986 horsepower. With just 1,200 miles from new, this example presents in immaculate condition and features Ferrari\'s most advanced technology to date. The SF90 Stradale sets new benchmarks for performance while also embracing hybrid technology, making it a significant model in Ferrari\'s illustrious history.""",
        "features": [
          "Assetto Fiorano Package",
          "Carbon Fiber Wheels",
          "Titanium Exhaust System",
          "Carbon Fiber Racing Seats",
          "Head-Up Display",
          "Carbon Fiber Engine Cover",
          "Suspension Lifter",
          "Premium JBL Sound System",
          "Carbon Fiber Rear Diffuser",
          "Track Telemetry System"
        ],
        "status": "Available"
      },
      {
        "make": "Ferrari",
        "model": "Purosangue",
        "year": 2024,
        "price": 425000,
        "mileage": 750,
        "exterior_color": "Rosso Mugello",
        "interior_color": "Nero",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "6.5L V12",
        "description": """The Ferrari Purosangue represents Ferrari\'s first four-door, four-seater model, combining the brand\'s racing DNA with unprecedented practicality. This stunning example in Rosso Mugello with Nero interior features the naturally aspirated 6.5-liter V12 engine producing 715 horsepower. With only 750 miles, this Purosangue showcases Ferrari\'s revolutionary active suspension system and all-wheel drive, delivering the pure Ferrari driving experience in a more versatile package.""",
        "features": [
          "Active Suspension System",
          "Carbon Fiber Roof",
          "Rear-Hinged Back Doors",
          "Four Individual Heated Seats",
          "Ferrari Dynamic Enhancer Plus",
          "Carbon Ceramic Brakes",
          "Side Slip Control 7.0",
          "Manettino Drive Mode Selector",
          "Premium Sound System",
          "Advanced Driver Assistance"
        ],
        "status": "Available"
      },
      {
        "make": "Lamborghini",
        "model": "Urus",
        "year": 2024,
        "price": 235000,
        "mileage": 2800,
        "exterior_color": "Giallo Auge",
        "interior_color": "Nero Alde",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "4.0L V8 Twin-Turbo",
        "description": """This Lamborghini Urus combines the soul of a super sports car with the versatility of an SUV. Finished in striking Giallo Auge with Nero Alde interior, this 657-horsepower beast accelerates from 0-60 mph in just 3.3 seconds. With 2,800 miles, this Urus represents the perfect blend of Lamborghini\'s racing heritage and everyday usability, featuring advanced all-wheel drive and multiple driving modes.""",
        "features": [
          "ANIMA Drive Mode Selector",
          "Active Anti-Roll Bars",
          "Air Suspension with Six Drive Modes",
          "Carbon Ceramic Brakes",
          "Lamborghini Infotainment System III",
          "Sport Exhaust System",
          "21-inch Nath Wheels",
          "Alcantara Sport Seats",
          "Advanced Driving Dynamics",
          "Rear-Wheel Steering"
        ],
        "status": "Available"
      },
      {
        "make": "Land Rover",
        "model": "Defender 110",
        "year": 2024,
        "price": 95000,
        "mileage": 4200,
        "exterior_color": "Carpathian Grey",
        "interior_color": "Ebony",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "5.0L V8",
        "description": """This Land Rover Defender 110 represents the perfect fusion of modern luxury and legendary capability. Finished in sophisticated Carpathian Grey with Ebony interior, this V8-powered Defender delivers 518 horsepower while maintaining its iconic rugged character. With 4,200 miles, it features advanced terrain response systems and luxury appointments that make it equally at home in the city or conquering the most challenging terrain.""",
        "features": [
          "Terrain Response 2",
          "All Terrain Progress Control",
          "ClearSight Ground View",
          "Configurable Terrain Response",
          "Wade Sensing",
          "Air Suspension",
          "Pivi Pro Infotainment",
          "3D Surround Camera",
          "Premium LED Headlights",
          "Expedition Roof Rack"
        ],
        "status": "Available"
      },
      {
        "make": "Range Rover",
        "model": "Sport",
        "year": 2024,
        "price": 125000,
        "mileage": 3500,
        "exterior_color": "Byron Blue",
        "interior_color": "Ebony/Ivory",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "4.4L V8",
        "description": """This Range Rover Sport delivers dynamic performance with luxury refinement. Presented in elegant Byron Blue with Ebony/Ivory interior, this example features the powerful 4.4-liter V8 engine producing 523 horsepower. With 3,500 miles, it combines Range Rover\'s legendary capability with sports car-inspired driving dynamics, making it the perfect choice for those who demand both luxury and performance.""",
        "features": [
          "Dynamic Response Pro",
          "Meridian Surround Sound System",
          "Heated and Cooled Seats",
          "Panoramic Roof",
          "Hands-Free Power Tailgate",
          "Digital Instrument Cluster",
          "Terrain Response 2",
          "Four-Zone Climate Control",
          "Matrix LED Headlights",
          "Mobile Hotspot"
        ],
        "status": "Available"
      },
      {
        "make": "Bentley",
        "model": "Bentayga",
        "year": 2024,
        "price": 185000,
        "mileage": 1800,
        "exterior_color": "Glacier White",
        "interior_color": "Saddle",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "4.0L V8",
        "description": "This Bentley Bentayga represents the pinnacle of luxury SUV motoring. Finished in pristine Glacier White with handcrafted Saddle leather interior, this example showcases Bentley\'s commitment to craftsmanship and performance. Powered by a twin-turbocharged 4.0-liter V8 engine producing 542 horsepower, with only 1,800 miles, it offers unparalleled luxury, advanced technology, and the versatility expected from the world\'s most luxurious SUV.""",
        "features": [
          "Mulliner Driving Specification",
          "Naim for Bentley Audio System",
          "All-Terrain Specification",
          "Rear Seat Entertainment",
          "Panoramic Glass Sunroof",
          "Adaptive Cruise Control",
          "Bentley Rotating Display",
          "Massage Function Seats",
          "Diamond Knurled Gear Lever",
          "City & Touring Specification"
        ],
        "status": "Available"
      },
      {
        "make": "Mercedes-Benz",
        "model": "S-Class S450 4MATIC AMG",
        "year": 2024,
        "price": 155000,
        "mileage": 2900,
        "exterior_color": "Designo Diamond Silver",
        "interior_color": "Black Nappa Leather",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "3.0L I6 Turbo",
        "description": """This Mercedes-Benz S450 4MATIC with AMG Line represents the epitome of luxury and technological innovation. Finished in sophisticated Designo Diamond Silver with Black Nappa leather interior, this flagship sedan features a turbocharged 3.0-liter inline-6 engine with EQBoost mild-hybrid technology producing 362 horsepower. With 2,900 miles, it showcases Mercedes-Benz\'s latest MBUX technology and comfort features.""",
        "features": [
          "MBUX Interior Assistant",
          "Burmester 4D Surround Sound",
          "Executive Rear Seat Package",
          "Active Body Control",
          "Digital Light Technology",
          "Energizing Comfort Control",
          "Hot Stone Massage",
          "Active Ambient Lighting",
          "Head-Up Display",
          "Driver Assistance Package"
        ],
        "status": "Available"
      },
      {
        "make": "Porsche",
        "model": "Cayenne",
        "year": 2024,
        "price": 105000,
        "mileage": 3100,
        "exterior_color": "Jet Black Metallic",
        "interior_color": "Bordeaux Red",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "3.0L V6 Turbo",
        "description": """This Porsche Cayenne delivers sports car performance in an SUV package. Finished in striking Jet Black Metallic with luxurious Bordeaux Red interior, this example features the turbocharged 3.0-liter V6 engine producing 348 horsepower. With 3,100 miles, it embodies Porsche\'s commitment to driving excellence while offering the practicality and versatility expected from a premium SUV.""",
        "features": [
          "Porsche Active Suspension Management",
          "Sport Chrono Package",
          "Bose Surround Sound System",
          "Panoramic Roof System",
          "Porsche Communication Management",
          "Air Suspension",
          "Lane Keeping Assist",
          "Adaptive Cruise Control",
          "ParkAssist",
          "Multi-Zone Climate Control"
        ],
        "status": "Available"
      },
      {
        "make": "Porsche",
        "model": "Panamera",
        "year": 2024,
        "price": 145000,
        "mileage": 2400,
        "exterior_color": "Crayon",
        "interior_color": "Black/Cognac",
        "fuel_type": "Petrol",
        "transmission": "Automatic",
        "engine_size": "2.9L V6 Twin-Turbo",
        "description": """This Porsche Panamera represents the perfect fusion of luxury grand touring and sports car performance. Finished in distinctive Crayon with Black/Cognac interior, this four-door sports sedan features a twin-turbocharged 2.9-liter V6 engine producing 325 horsepower. With only 2,400 miles, it offers exceptional comfort for four passengers while maintaining Porsche\'s legendary driving dynamics and build quality.""",
        "features": [
          "Porsche Active Suspension Management",
          "Sport Chrono Package",
          "Bose Surround Sound System",
          "Four-Zone Climate Control",
          "Porsche Communication Management",
          "Adaptive Cruise Control",
          "Lane Change Assist",
          "ParkAssist with Surround View",
          "Sport Seats Plus",
          "Premium Package Plus"
        ],
        "status": "Available"
      }
    ];

class Command(BaseCommand):
    help = "Seeds the database with vehicle data"

    def handle(self, *args, **options):
        Vehicle.objects.all().delete()
        for car in CARS:
            vehicle = Vehicle.objects.create(
                make=car["make"],
                model=car["model"],
                year=car["year"],
                price=car["price"],
                mileage=car["mileage"],
                exterior_color=car["exterior_color"],
                interior_color=car["interior_color"],
                fuel_type=car["fuel_type"],
                transmission=car["transmission"],
                engine_size=car["engine_size"],
                description=car["description"],
                features=car["features"],
                status=car["status"]
            )
        self.stdout.write(self.style.SUCCESS("Successfully seeded vehicles"))
